sudo: required

language: python

python:
  - "3.5"

services:
  - mysql
  - docker

install:
  - pip3 install -q Django==1.10
  - pip3 install mysqlclient==1.3.7
  - pip3 install requests==2.9.1
  - pip3 install docker-compose

script: 
  - python app/manage.py test

before_script:
  - docker pull mysql:5.7.14
  - mkdir -p ~/cs4501/db/
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - sleep 45s
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 bash -c "mysql -uroot -p'$3cureUS' -h db"
  - docker-compose up

